"""notifications and support inquiries

Revision ID: 10f5ea802def
Revises: 8b9f19bc567e
Create Date: 2026-09-26 14:02:57.475687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f5ea802def'
down_revision = '8b9f19bc567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('payment_due', 'class_reminder', 'attendance_update', 'support_reply')", name='ck_notification_kind'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_user_dedupe')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('support_inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('general', 'payment', 'attendance', 'technical')", name='ck_inquiry_category'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved')", name='ck_inquiry_status'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_inquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_inquiry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_inquiry_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_inquiry_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_inquiry_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_inquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_inquiry_student_id'))
        batch_op.drop_index(batch_op.f('ix_support_inquiry_status'))
        batch_op.drop_index(batch_op.f('ix_support_inquiry_sender_id'))
        batch_op.drop_index(batch_op.f('ix_support_inquiry_created_at'))

    op.drop_table('support_inquiry')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    # ### end Alembic commands ###
